<?php require __DIR__.'/../includes/bootstrap.php'; require_client();
$error=''; $drums=db()->query('SELECT id,name,description,hourly_rate FROM drums WHERE is_active=1 ORDER BY name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$drumId=filter_var($_POST['drum_id']??null,FILTER_VALIDATE_INT);$start=trim($_POST['start_at']??'');$duration=filter_var($_POST['duration_hours']??null,FILTER_VALIDATE_INT);$purpose=trim($_POST['purpose']??'');$notes=trim($_POST['notes']??'');
 if(!$drumId || !$duration || $duration<1 || $duration>12) $error='Choose a drum and a duration from 1 to 12 hours.';
 elseif($purpose===''||mb_strlen($purpose)>120) $error='Enter a session purpose (up to 120 characters).';
 elseif(mb_strlen($notes)>1000) $error='Notes must be 1,000 characters or fewer.';
 else { $dt=DateTime::createFromFormat('Y-m-d\TH:i',$start); $now=new DateTime('now'); if(!$dt||$dt->format('Y-m-d\TH:i')!==$start||$dt<=$now||$dt->getTimestamp()>$now->getTimestamp()+365*86400) $error='Choose a valid future date and time within the next year.';
  else { try { $pdo=db();$pdo->beginTransaction();$s=$pdo->prepare('SELECT id,hourly_rate FROM drums WHERE id=? AND is_active=1 FOR UPDATE');$s->execute([$drumId]);$drum=$s->fetch();if(!$drum) throw new RuntimeException('That drum is no longer available.');$end=(clone $dt)->modify('+'.$duration.' hours');$s=$pdo->prepare("SELECT COUNT(*) FROM bookings WHERE drum_id=? AND status IN ('Pending','Approved') AND start_at < ? AND end_at > ?");$s->execute([$drumId,$end->format('Y-m-d H:i:s'),$dt->format('Y-m-d H:i:s')]);if((int)$s->fetchColumn()>0) throw new RuntimeException('That drum is already booked during the selected time. Please choose another time.');$total=(float)$drum['hourly_rate']*$duration;$s=$pdo->prepare("INSERT INTO bookings(user_id,drum_id,start_at,end_at,duration_hours,purpose,notes,total_price,status) VALUES(?,?,?,?,?,?,?,?, 'Pending')");$s->execute([user()['id'],$drumId,$dt->format('Y-m-d H:i:s'),$end->format('Y-m-d H:i:s'),$duration,$purpose,$notes,$total]);$pdo->commit();flash('success','Booking request submitted. An admin must approve it.');redirect('index.php'); }catch(RuntimeException $ex){if(db()->inTransaction())db()->rollBack();$error=$ex->getMessage();}catch(Throwable $ex){if(db()->inTransaction())db()->rollBack();error_log($ex->__toString());$error='We could not save your booking. Please try again.';} }
 }
}
page_header('Book a drum'); ?><div class="form-card"><p class="muted">Complete the form below. Your request will be marked <strong>Pending</strong> until an admin reviews it.</p><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><?php if(!$drums):?><div class="alert error">There are currently no drums available for booking.</div><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="grid two"><label>Full name<input value="<?=e(user()['name'])?>" readonly></label><label>Email address<input value="<?=e(user()['email'])?>" readonly></label><label>Contact number<input value="<?=e(user()['phone']??'')?>" readonly><small>Update your contact details by contacting the administrator.</small></label><label>Drum kit<select name="drum_id" required><option value="">Select a drum kit</option><?php foreach($drums as $d):?><option value="<?=(int)$d['id']?>" <?=((string)($drumId??'')===(string)$d['id'])?'selected':''?>><?=e($d['name'])?> — <?=money($d['hourly_rate'])?>/hour</option><?php endforeach;?></select></label><label>Session date and time<input type="datetime-local" name="start_at" min="<?=e(date('Y-m-d\TH:i',time()+60))?>" required value="<?=e($start??'')?>"></label><label>Duration<select name="duration_hours" required><?php for($i=1;$i<=12;$i++):?><option value="<?=$i?>" <?=((string)($duration??'1')===(string)$i)?'selected':''?>><?=$i?> hour<?=$i>1?'s':''?></option><?php endfor;?></select></label><label class="span-2">Purpose of session<input name="purpose" maxlength="120" placeholder="e.g., Band practice, recording, personal practice" required value="<?=e($purpose??'')?>"></label><label class="span-2">Additional notes <span class="muted">(optional)</span><textarea name="notes" maxlength="1000" rows="4" placeholder="Anything the studio should know?"><?=e($notes??'')?></textarea></label></div><div class="actions"><button class="button" type="submit">Submit booking request</button><a class="button secondary" href="index.php">Cancel</a></div></form><?php endif;?></div><?php page_footer();
